- hosts: builder
  tasks:
    - name: install dependencies
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - python2-virtualenv
        - ShellCheck
        - python2-devel
        - make
        - python2-pip
        - python2-wheel
        - tox
        - libffi-devel
        - openssl-devel
        - libeselinux-python

    - name: create docker group
      become: true
      group:
        name: docker
        state: present

    - name: add Jenkins user to docker group
      become: true
      user:
        name: jenkins
        groups: docker
        append: true
        state: present
      register: group_added

    - name: start Docker service
      become: true
      service:
        name: docker
        state: started
        enabled: true

    - name: restart swarm to pick up new jenkins group
      become: true
      service:
        name: swarm
        state: restarted
      when: group_added|changed
