- hosts: builder
  tasks:
    - name: install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - python-tox
        - python-virtualenv
        - ShellCheck
        - python-devel
        - make
        - python34
        - python34-devel

    - name: create docker group
      group:
        name: docker
        state: present

    - name: add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: true
        state: present
      register: group_added

    - name: start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: restart swarm to pick up new jenkins group
      service:
        name: swarm
        state: restarted
      when: group_added|changed
