- name: wait for Jenkins
  include: ensure_up.yml

- set_fact:
    script: "{{ lookup('file', role_path + '/templates/groovy_set_jenkins_cfg.java') }}"

- name: run Jenkins global config
  jenkins_script:
    url: "{{ _jenkins_url }}"
    script: "{{ script }}"
    validate_certs: false
    args:
      jenkins_executors: "{{ jenkins_executors }}"
      jenkins_slave_agent_port: "{{ jenkins_slave_agent_port }}"
  register: script_output

- name: configure update centers
  jenkins_update_center:
    update_center_id: "{{ item.id }}"
    update_center_url: "{{ item.url }}"
  with_items: "{{ update_centers }}"
  notify: restart Jenkins
  become_user: jenkins
  become: true

- name: create cert path
  file:
    dest: "{{ jenkins_home }}/update-center-rootCAs"
    state: directory
    owner: jenkins
    group: jenkins

- name: copy cert file
  copy:
    src: "{{ update_center_certificate }}"
    dest: "{{ jenkins_home }}/update-center-rootCAs/update-center.crt"
    owner: jenkins
    group: jenkins
  notify: restart Jenkins
  when: update_center_certificate is defined

- name: force handlers
  meta: flush_handlers

- name: wait for jenkins master
  include: ensure_up.yml

- name: perform plugin install
  jenkins_plugin:
    url: "{{ _jenkins_url }}"
    name: "{{ item.split('=')[0] }}"
    state: present
    version: "{{ item.split('=')[2] | default(omit) }}"
  register: plugin_install
  retries: 3
  until: not plugin_install|failed
  with_items: "{{ jenkins_plugins }}"
  notify: restart Jenkins

- name: flush handlers
  meta: flush_handlers
