# systemd: daemon_reload=yes can be used in Ansible 2.4
- name: reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: restart nginx service
  service:
    name: nginx
    state: restarted
