require "../shared.rb"

Vagrant.configure("2") do |config|
    vm(config, "master", "generic/rhel8")
    vm(config, "slave", "generic/rhel8") do |ansible|
        ansible.groups = {
            "jenkins_master" => ["master"],
            "jenkins_slave" => ["slave"],
            "rhel8" => ["master", "slave"],
            "repositories" => ["master", "slave"],
            "jenkins_slave:vars" => {
                "jenkins_master_url" => "http://{{ hostvars['master']['ansible_default_ipv4']['address'] }}"
            },
            "rhel8:vars" => {
				"rhel_base" => "http://example.com/content/beta/rhel8/8/x86_64/"
            }
        }
    end
end
